#+STARTUP: showall indent hidestars

* sudo

#+BEGIN_SRC sh
  apt-get install sudo
#+END_SRC

чтобы при использовании команды sudo спрашивало
пароль не пользователя, а root-а, нужно в sudoers раскомментировать
следующую строку:

#+BEGIN_SRC
  default targetpw
#+END_SRC

* mc

#+BEGIN_SRC sh
  sudo apt-get install mc
#+END_SRC

* sshfs

#+BEGIN_SRC sh
  sudo apt-get install sshfs
#+END_SRC

* git

#+BEGIN_SRC sh
  sudo apt-get install git-core
#+END_SRC
* tig

#+BEGIN_SRC sh
  sudo apt-get install tig
#+END_SRC

* gimp

#+BEGIN_SRC sh
 sudo apt-get install gimp
#+END_SRC

* yEd

#+BEGIN_SRC sh
  cd build
  wget https://www.yworks.com/resources/yed/demo/yEd-3.19_with-JRE8_64-bit_setup.sh
  chmod +x ./yEd-3.19_with-JRE11_64-bit_setup.sh
  sudo sh ./yEd-3.19_with-JRE11_64-bit_setup.sh
#+END_SRC

* wireshark

#+BEGIN_SRC sh
 apt-get install wireshark
#+END_SRC

* lamp

#+BEGIN_SRC sh
  sudo tasksel install lamp-server
  port 8080
  error: Could not reliably determine the server’s fully qualified...
  to /etc/apache2/httpd.conf : "ServerName localhost"
#+END_SRC

* openssh

#+BEGIN_SRC sh
  apt-get install openssh-server
#+END_SRC
* nginx

nginx умеет fastcgi: http://nginx.localdomain.pl/wiki/FcgiWrap

* cgit

http://habrahabr.ru/blogs/linux/86753/
Файлы логов виртуальных хостов должны существовать!
Чтобы веб-сервер имел доступ к папке где лежит .htaccess надо
поставить права ...-xr-x на всю цепочку папок
a2enmod rewrite
http://linuxdoc.pp.ru/content/cgit-%D0%B8-apache

* gitosis

http://meandubuntu.ru/2009/12/%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-git-%D0%B8-gitosis-%D0%B2-ubuntu/
http://scie.nti.st/2007/11/14/hosting-git-repositories-the-easy-and-secure-way
При добавлении нового репозитория проверить совпадение имен в ключах
пользователей и имен в gitosis.conf. Не забыть пушнуть gitosis.conf
Пушить новый репозиторий при создании с помощью git push origin
master:refs/heads/master

* xbindkeys-config

#+BEGIN_SRC
  sudo apt install xbindkeys-config
#+END_SRC

* xdotool

xte
xvkbd
xprop

https://habr.com/ru/post/266375/

#+BEGIN_SRC
  sudo apt install xdotool
#+END_SRC

* seltr

По мотивам: https://habr.com/en/post/137215/

Очень простой интерфейс для отправки уведомлений из консоли предоставляет утилита
notify-send, которую можно найти в пакете libnotify-bin.

Пример:

#+BEGIN_SRC sh
  notify-send 'title' 'message'
#+END_SRC

Для получения текущего выделения в X Window System используется утилита xsel. Её надо
поставить:

#+BEGIN_SRC sh
  sudo apt install xsel
#+END_SRC

Теперь, чтобы получить текущее выделение в поток ввода из командной строки можно ввести:

#+BEGIN_SRC sh
  xsel -o
#+END_SRC

Создаём файл с именем /usr/bin/seltr и копируем в него следующие строки:

#+BEGIN_SRC sh
  #!/usr/bin/env bash
  TR="$(\
         wget -U "Mozilla/5.0" -qO -\
             "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=ru&dt=t&q=\
                $(\
                    xsel -o | sed "s/[\"'<>]//g"\
                )\
             "\
         | sed '/^\,\[\"en\"\]$/d;'\
         | sed 's/\"\,\".*$//;'\
         | sed 's/^\[\[\[\"/\,\[\"/;'\
         | sed '/^\,\[\".*$/!d;'\
         | sed 's/^\,\[\"//;'\
     )"
  notify-send -u critical --icon=info "$TR" "$TR"
#+END_SRC

Или, если вы предпочитате краткую форму:

#+BEGIN_SRC sh
  #!/usr/bin/env bash
  TR="$(wget -U "Mozilla/5.0" -qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=ru&dt=t&q=$(xsel -o | sed "s/[\"'<>]//g")" \
   | sed '/^\,\[\"en\"\]$/d;s/\"\,\".*$//;s/^\[\[\[\"/\,\[\"/;/^\,\[\".*$/!d;s/^\,\[\"//;')"
  notify-send -u critical --icon=info "$TR" "$TR"
#+END_SRC


Цепочки SED сделаны так, чтобы иметь возможность их выборочно отключать при
отладке. Их назначение:
- удаляет строки =["en"]=
- обрезает каждую строку начиная с =","= и до ее конца
- заменяет в начале каждой строки =[[["= на =["=
- удаляет все строки кроме начинающихся с =,["=
- удаляет =,["= в начале каждой из оставшихся строк


#+BEGIN_SRC sh
  chmod 777 /usr/bin/seltr
  sudo apt-get install xbindkeys

  xbindkeys --defaults > ~/.xbindkeysrc
#+END_SRC

Добавляем в ~/.xbindkeys

#+BEGIN_SRC sh
  "seltr"
  control+shift + m
#+END_SRC

* TODO dia - для работы со схемами в линукс
* TODO vnc
* TODO qfsm
скачан но не поставлен
* TODO conky
* rar/unrar

#+BEGIN_SRC sh
  apt-get install rar unrar
#+END_SRC

* imagemagic

#+BEGIN_SRC sh
  sudo apt install libmagickcore-dev libmagickwand-dev
#+END_SRC

* emacs

#+BEGIN_SRC sh
  sudo apt install libmagickcore-dev libmagickwand-dev
  wget http://mirror.tochlab.net/pub/gnu/emacs/emacs-26.3.tar.xz
  untar
  cd emacs-26.3
  ./configure --with-imagemagick # это важно для телеги!
  make
  sudo make install
#+END_SRC

слить .emacs.d и jabber-accounts.el

** telega el

https://github.com/zevlg/telega.el

#+BEGIN_SRC sh
  sudo apt-get update
  sudo apt-get upgrade
  sudo apt-get install make git zlib1g-dev libssl-dev gperf php cmake g++
  git clone https://github.com/tdlib/td.git
  cd td
  rm -rf build
  mkdir build
  cd build
  export CXXFLAGS=""
  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local ..
  cmake --build . --target install
  cd ..
  cd ..
  ls -l /usr/local
#+END_SRC

#+BEGIN_SRC sh
  git clone https://github.com/zevlg/libtgvoip.git
  cd libtgvoip
  autoreconf --force --install && ./configure && make
  sudo make install
#+END_SRC

#+BEGIN_SRC sh
  sudo ldconfig
#+END_SRC

** emacs-jabber

#+BEGIN_SRC sh
  cd ~/.emacs.d
  git clone
  git://emacs-jabber.git.sourceforge.net/gitroot/emacs-jabber/emacs-jabber
  autoreconf -i
  ./configure
  make
#+END_SRC

** mailcrypt

** dict

https://ladycat.wordpress.com/2013/03/13/dict_n_dictem_n_emacs/

#+BEGIN_SRC sh
  aptitude install dict dictd dictem
#+END_SRC

Скачиваем словаль mueller отсюда:
https://sourceforge.net/projects/mueller-dict/

Распаковыаем, потом:

#+BEGIN_SRC sh
  ./configure
  make
  sudo make install
#+END_SRC

Идем в =/etc/dictd.conf= и добавляем в него:

#+BEGIN_SRC conf
  database mueller-abbrev {
  data  /usr/local/share/dict/mueller-abbrev.dict.dz
  index /usr/local/share/dict/mueller-abbrev.index
  }
  database mueller-base {
  data  /usr/local/share/dict/mueller-base.dict.dz
  index /usr/local/share/dict/mueller-base.index
  }
  database mueller-dict {
  data  /usr/local/share/dict/mueller-dict.dict.dz
  index /usr/local/share/dict/mueller-dict.index
  }
  database mueller-geo {
  data  /usr/local/share/dict/mueller-geo.dict.dz
  index /usr/local/share/dict/mueller-geo.index
  }
  database mueller-names {
  data  /usr/local/share/dict/mueller-names.dict.dz
  index /usr/local/share/dict/mueller-names.index
  }
#+END_SRC

Посылаем SIGHUP демону =dictd=, чтобы он перечитал конфигурацию

#+BEGIN_SRC sh
  ps -aux | grep dictd
  dictd     2950    0:00 dictd 1.12.1: 1/12
  root      4198    0:00 grep --color=auto dictd

  kill -s SIGHUP 2950
#+END_SRC

Если вдруг захочется использовать нелокальный словарь, то в файле
=/etc/dictd/dict.conf= (не путать с =dictd.conf= можно раскомментировать:

#+BEGIN_SRC conf
  server localhost
  #server dict.org
  #server dict0.us.dict.org
  #server alt0.dict.org
#+END_SRC

список в файле =/var/lib/dictd/db.list= создается автоматически c помощью
DICTDCONFIG(8), поэтому его редактировать не нужно.

В файле =/etc/dictd/dictd.order= настраиваем порядок просмотра локальным сервером dictd
баз данных англо-русских словарей

#+BEGIN_SRC conf
  # This file defines the order in which dictdconfig lists dictionaries
  # in /var/lib/dictd/db.list.  The entry "/usr/share/dictd/" brings in
  # any dictionaries in that directory that aren't specifically listed
  # in this file.  You should enter the names of the dictionaries you
  # have installed, in the order you would prefer to have them searched.

  mueller-base  mueller-dict  mueller-geo  mueller-names  mueller-abbrev
  /usr/share/dictd/
#+END_SRC


** ditaa

#+BEGIN_SRC sh
  sudo apt install ditaa
#+END_SRC

** gnuplot

#+BEGIN_SRC sh
  sudo apt install ditaa
#+END_SRC

** plantuml

https://real-world-plantuml.com/

#+BEGIN_SRC sh
  sudo apt install plantuml
#+END_SRC



** graphviz

#+BEGIN_SRC sh
  sudo apt install graphviz
#+END_SRC

** mpd

#+BEGIN_SRC sh
  sudo apt install mpd
#+END_SRC

* Permdenied USB-port fix

#+BEGIN_SRC sh
  sudo usermod -a -G dialout $USER
#+END_SRC

* avrdisas

Download: https://www.johannes-bauer.com/mcus/avrdisas/

#+NAME:
#+BEGIN_SRC sh
  make
  sudo make install
#+END_SRC
* llvm cmake

#+BEGIN_SRC
  cd ~/build
  git clone https://github.com/llvm/llvm-project.git
  cd llvm-project
  mkdir build
  cd builds
  cmake -DLLVM_ENABLE_PROJECTS=clang -G "Unix Makefiles" ../llvm
  make
  make install
#+END_SRC

* tcl

#+BEGIN_SRC
  sudo apt-get install tcl8.5 tk8.5 tcllib libsqlite3-tcl libtk-img
#+END_SRC

* opera

opera.com - tar.gz - sh install
* chrome

google.com - package install

* skype

#+BEGIN_SRC sh
  wget http://www.skype.com/go/getskype-linux-beta-ubuntu-32
  sudo apt-get install libqt4-dbus libqt4-network libqt4-xml libasound2
#+END_SRC

* autoconf

#+BEGIN_SRC sh
  sudo apt-get install autoconf
#+END_SRC

* texinfo

#+BEGIN_SRC sh
  sudo apt-get install texinfo
#+END_SRC

* conkeror

#+BEGIN_SRC sh
  sudo apt-get install conkeror
#+END_SRC

* YOTA

http://forum.ubuntu.ru/index.php?topic=94235.0

#+BEGIN_SRC sh
  sudo apt-get install madwimax
#+END_SRC

затем  создать файл ~/etc/udev/rules.d/60-madwimax.rules~
с сoдержимым:

#+BEGIN_SRC sh
  # udev rules file for madwimax supported devices
  SUBSYSTEM!="usb|usb_device", GOTO="madwimax_rules_end"
  ACTION!="add", GOTO="madwimax_rules_end"
  ATTR{idVendor}=="04e8", ATTR{idProduct}=="6761", RUN+="//sbin/madwimax -qdof --exact-device=$attr{busnum}/$attr{devnum}"
  ATTR{idVendor}=="04e9", ATTR{idProduct}=="6761", RUN+="//sbin/madwimax -qdof --exact-device=$attr{busnum}/$attr{devnum}"
  LABEL="madwimax_rules_end"
#+END_SRC

* FIREFOX
** Чтобы не переключался в автономный режим
в адресной строке firefox
about:config -> toolkit.networkmanager.disable -> в положение true
** Flash
Сам предложит
** Firemax
** Firebug
** Colorzilla
** Readability
** Настройки
Снять галку "Запоминать пароли для сайтов"

* sbcl

#+BEGIN_SRC sh
sbcl.org download install
chmod +x cache fasls
#+END_SRC

* slime

слить quicklisp и .emacs.d

* quicklisp

copy quicklisp folger from home mashine

* org-mode

Устанавливаем из официального репозитория

#+BEGIN_SRC sh
  cd ~/src/
  git clone https://code.orgmode.org/ewestbrook/org-mode.git
  cd org-mode/
  make autoloads
  make
#+END_SRC

Добавляем в ~/.emacs.d/init.el если еще нет

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/src/org-mode/lisp")
  (add-to-list 'load-path "~/src/org-mode/contrib/lisp" t)
#+END_SRC

* Lenovo Thinkpad Touchpad Problem

solution from https://forums.lenovo.com/t5/Other-Linux-Discussions/Troubles-with-X1-Carbon-2018-X1C6-TouchPad-and-TrackPoint-under/td-p/4004815

remove "i2c_i801" from /etc/modprobe.d/blacklist.conf

in etc/default/grub:

#+BEGIN_SRC conf
  GRUB_CMDLINE_LINUX_DEFAULT="quiet splash psmouse.synaptics_intertouch=1"
#+END_SRC

after it:

#+BEGIN_SRC sh
  sudo grub-mkconfig =o /boot/grub/grub.cfg
  sudo reboot now
#+END_SRC
